# Awesome.  See https://github.com/gtassone/dropwizard-archetype.git where I got this code from

response: "response is: Docker Hello App"
defaultHtmlResourceLocation: "/html"

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
    - type: file
      currentLogFilename: /logs/cdowns.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /logs/cdowns-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"